### ISSUE TITLE
downloadcfg not working

### ISSUE THREAD

**Issue by anfo55** [Serivy/HG659-VOIP-Password#1]
Hi
My Huawei HG659 (TPG) modem IP currently is 192.168.1.200, however after logging in with admin/admin and inputting address http://192.168.1.200/api/system/downloadcfg no file downloads and nothing else happens. Is my syntax correct?

I'm also wondering whether Huawei/TPG have updated FW in the year and a half since you created your tool?

**Comment by Serivy** [comment]
It's possible. I just tried it then and it worked. 
Hardware version: VER.B
Software version: V100R001C216B111

![config dl](https://user-images.githubusercontent.com/9199253/49372149-ae558380-f734-11e8-8de6-59aad6a144c8.gif)

You could try the root account from the post: 
https://forums.whirlpool.net.au/forum-replies.cfm?t=2618801&#r13

**Comment by anfo55** [comment]
Thank you for your reply. My modem:
Hardware version:	VER.B
Software version:	V100R001C216B113

I suspect Huawei and/or TPG have perhaps cottoned on to this and have possibly secured both aspects. That is, root account is now invalid (reports incorrect password) and downloadconfig does not initiate.

**Comment by anfo55** [comment]
I'm not sure if I should hold out for a solution, otherwise I will retire the modem in favour for new VOiP hardware and provider.

**Comment by Serivy** [comment]
I am trying to think of ways to get the config but if its unobtainable now there there will be nothing to decrypt. Is your ISP TPG or IINet? I noticed that if you get IINet HFC today they give a iinet branded modem now instead of this HG659.

Under root there is a download config button.
![image](https://user-images.githubusercontent.com/9199253/49500675-34e0a100-f8ac-11e8-84d0-9f1102a063c3.png)
which calls window.download_cfg();
![image](https://user-images.githubusercontent.com/9199253/49501455-dcaa9e80-f8ad-11e8-84b0-90254c17b6dc.png)

Can you check your chrome console for those commands?

**Comment by anfo55** [comment]
It's an old TPG modem. So you say under device management the backup button will download the config file as well? I will look for it. However you also mention the term root and if you look up a few comments I said that account doesn't work unfortunately.

**Comment by Serivy** [comment]
Yeah I get what you're saying. Chances are admin users no longer have the ability to get the required configuration settings. IINet wont support you unless you're using their router too.

**Comment by MeatyBytes** [comment]
The following works for me if anyone is still trying to figure out how to login as admin.
After logging as admin, you will then be able to go to the device manager page and save the config file from there (Which points to the /api/ page).

![image](https://user-images.githubusercontent.com/11422020/183302888-87209dc6-0641-4dd3-a808-88346d7c2530.png)


Jot down the serial and MAC address found at the back of the HG659.

eg

Serial number: J3N8W1640700**1310**
MAC: C4F081F5**5BC6**
The USERNAME should be the last 4 digits of the serial & mac address
**13105BC6**

Serial number: J3N8W16407**001310**
MAC: C4F081**F55BC6**
The PASSWORD should be @ concatenated with the last 6 digits of the serial & mac address
**@001310F55BC6**

**Comment by Serivy** [comment]
Thank you, linked your comment to the readme.md!
