### ISSUE TITLE
decryptfile not working

### ISSUE THREAD

**Issue by omgitsheaven** [Serivy/HG659-VOIP-Password#2]
The ps1 isn't decrypting the config file. I get an error that the downloadconfigfile.conf does not exist. Even though the conf file is in the same folder.

By the way, im using a HG659 provided by Vodafone on firmware B026

**Comment by Serivy** [comment]
You could try specifying the full path to the config file. Perhaps even move it to a simple location like C:\
`.\DecryptConfig.ps1 C:\downloadconfigfile.conf`

**Comment by omgitsheaven** [comment]
Ok I've tried to do .\DecryptConfig.ps1 C:\downloadconfigfile.conf

However now I get this error,

![error with decription](https://user-images.githubusercontent.com/30207734/57007444-d04c2700-6c3c-11e9-8943-c55790b22c8d.PNG)

**Comment by Serivy** [comment]
Interesting, It seems to be failing on the decompression step so it isn't to do with decryption keys (yet). You say your on version B026
which looks to be older than my version. Can you paste the entire version string under Maintain > System Information.
EG:
Hardware version: VER.B
Software version: V100R001C216B111

If you open up downloadconfigfile.conf in notepad, does it look like its a binary file? (eg start with things like "彵둆ⴱ턵䨧⩿")

**Comment by LouDnl** [comment]
I have the same problem. The conf file is a binary file for sure.
I tried debugging the problem, but my lack of powershell knowledge makes me unable to solve it.

The $memStreamFile variable (on windows) does have length:
`CanRead      : True
CanSeek      : True
CanWrite     : True
Capacity     : 10400
Length       : 10400
Position     : 2
CanTimeout   : False
ReadTimeout  :
WriteTimeout :`

But the $deflate variable (on windows) does not:
`BaseStream   : System.IO.MemoryStream
CanRead      : True
CanWrite     : False
CanSeek      : False
Length       :
Position     :
CanTimeout   : False
ReadTimeout  :
WriteTimeout :`

**Error on Linux:**

> ./DecryptConfig.ps1
> Exception calling "CopyTo" with "1" argument(s): "The archive entry was compressed using an unsupported compression method."
> At DecryptConfig.ps1:45 char:1
> + $deflate.CopyTo($destStream);
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
> + FullyQualifiedErrorId : InvalidDataException

**Error on Windows (in dutch sorry):**

> Exception calling "CopyTo" with "1" argument(s): "Bloklengte komt niet overeen met de aanvulling."
> At DecryptConfig.ps1:51 char:1
> + $deflate.CopyTo($destStream);
> + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> + CategoryInfo          : NotSpecified: (:) [], ParentContainsErrorRecordException
> + FullyQualifiedErrorId : InvalidDataException

**Comment by LouDnl** [comment]
Ps. The Python script you referenced fails with "Bad config file...exiting"

**Comment by Serivy** [comment]
It's pretty much a direct port of the python script so probably fails for the same reason. It's possible the binary file is slightly different or not compressed but just encrypted.

You could try not reading off the first two bytes by deleting lines 41-42.
You could also try removing the un-compress step by removing lines 40 to 45 and changing line 46 to $outputBytes = $memStreamFile.ToArray();

I would be happy to take a look if i could get my hands on one of the config files but I understand it has sensitive data in it. For my ISP if i did a factory reset it would not have my details until it was connected to the HFC modem, i am unsure of your situation but if you think you can purge your sensitive data from the config I could play around with trying to decode it.

**Comment by LouDnl** [comment]
Do you have Discord?

**Comment by Serivy** [comment]
I do, Feel free to join this server: https://discord.gg/SarPYYQ

**Comment by omgitsheaven** [comment]
> Interesting, It seems to be failing on the decompression step so it isn't to do with decryption keys (yet). You say your on version B026
> which looks to be older than my version. Can you paste the entire version string under Maintain > System Information.
> EG:
> Hardware version: VER.B
> Software version: V100R001C216B111
> 
> If you open up downloadconfigfile.conf in notepad, does it look like its a binary file? (eg start with things like "彵둆ⴱ턵䨧⩿")

Hey,

This is what my downloadconfigfile looks like when I open it in Notepad.
![downloadconfig snippet](https://user-images.githubusercontent.com/30207734/57175366-48198c00-6e9f-11e9-93f9-306281ce1c26.PNG)



This is my firmware version:
Hardware version:
VER.B
Software version:
V100R001C206B026

Thanks

**Comment by trunone** [comment]
I have the same issue.
I think it's the key is not correct.

ISP: T-Mobile NL
Firmware: V100R001C243B032

**Comment by fionny** [comment]
Anyone get this working... I really just need the SU password or to be able to change the VDSL addresses on the modem? VF have it locked down in Ireland and changed the SU password some time back so the ones online dont work.

**Comment by TorutheRedFox** [comment]
> Anyone get this working... I really just need the SU password or to be able to change the VDSL addresses on the modem? VF have it locked down in Ireland and changed the SU password some time back so the ones online dont work.

literally in the very same situation, except that I want to unlock ports 80 and 443 because I need to forward them

**Comment by minanagehsalalma** [comment]
> would be happy to take a look if i could get my hands on one of the config files

@Serivy  how can i send you it ?

**Comment by MeatyBytes** [comment]
I have made the script work by updating the keys,
New keys below (@Serivy - Maybe you can update the repo with the below code?.  I was able to use the below to decrypt the downloaded file.  I have also posted an update on how to login as admin.  I was able to use the DecryptPassword,ps1 script without making any updates.  I have successfully tested the VOIP details work on a TP-Link Deco X73 - In DSL mode):
```
# this Key & IV worked for previous versions of firmware (prior to 16V100R001C206B026), including Spark & BigPipe branded HG659b, and Huawei branded HG659
#[byte[]] $aesKeyBytes = 26, 170, 180, 167, 48, 178, 62, 31, 200, 161, 213, 156, 121, 40, 58, 34, 139, 120, 65, 14, 204, 70, 250, 79, 72, 235, 20, 86, 226, 76, 91, 137
#[byte[]] $aesIvBytes = 209, 254, 117, 18, 50, 92, 87, 19, 211, 98, 211, 50, 175, 163, 100, 76
# updated Key & IV for Vodafone NZ HG659 / iPrimus AU HG659 with firmware 16V100R001C206B026
[byte[]] $aesKeyBytes = 111,71,150,7,247,166,98,178,107,239,145,142,36,34,149,182,73,231,23,237,132,216,12,148,79,160,170,154,38,54,63,135
[byte[]] $aesIvBytes = 196,131,104,254,2,139,169,46,131,21,78,58,177,92,203,120

```

Updated link to the python version of the script, where I grabbed the keys from:
https://pastebin.com/qaLL6qTz

**Comment by Serivy** [comment]
Thanks @MeatyBytes I have updated the file with your changes and credited you. Champ.
